GameExe:Enemy1.o main.o Rand_Move.o
	gcc Enemy1.o main.o Rand_Move.o -o GameExe -lSDL -lSDL_image -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -g
Enemy1.o:Enemy1.c
	gcc -c Enemy1.c -lSDL -lSDL_image -g
Rand_Move.o:Rand_Move.c
